/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gracilianomp' at '12/14/14 6:28 PM' with Gradle 2.1
 *
 * @author gracilianomp, @date 12/14/14 6:28 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
